### ISSUE TITLE
BUG: Game in session

### ISSUE THREAD

**Issue by benjaminmodayil** [femioladeji/slack-words#16]
Hi 👋

Fun game, but our team ran into an issue:

![image](https://user-images.githubusercontent.com/12306850/75911226-3be2c000-5e1d-11ea-8b9c-1153633ee5ff.png)

Is there any command to reset the bot? I assume an uninstall/reinstall would be good enough, but just wondering if there was anything available.

**Comment by femioladeji** [comment]
@benjaminmodayil I completely missed this. Can you try it again now? I'm sorry for the delay.

I'll look into preventing this from happening again

**Comment by benjaminmodayil** [comment]
No worries about the delay! Appreciate you responding and definitely take your time! We found out that an immediate "reset" is just starting the game in another channel. But we broke it again and aren't sure what caused it this time. I tried out the bot in the channel that it originally broke in and it now works. I guess there is a time delay to reset it?

Here are some screenshots from a coworker that somehow broke it in our latest go:
![image](https://user-images.githubusercontent.com/12306850/76978746-78c6b080-690d-11ea-89ab-9d31c422581c.png)
![image](https://user-images.githubusercontent.com/12306850/76978845-98f66f80-690d-11ea-9366-2dfbbaeb7ded.png)
![image](https://user-images.githubusercontent.com/12306850/76978885-a1e74100-690d-11ea-8164-0f74b3cb0eaa.png)

**Comment by benjaminmodayil** [comment]
Despite my coworker's username, he wasn't use a special character set on his keyboard. Just his name has a different language set. But this hasn't broken it multiple times before.

**Comment by femioladeji** [comment]
@benjaminmodayil I need to dig a little more into this. I'll get back to you soon. Thanks for reporting this

**Comment by femioladeji** [comment]
@benjaminmodayil I've investigated the bug and I discovered one of the slack APIs is not returning the right data. Can you please re-install the app. This is a strange bug that only seems to be happening in your slack workspace
